module BufferApp {
    interface Buffer {
       long num_elementos();
         boolean put(in string elemento);
         boolean get(out string elemento);
         boolean read(out string elemento);
         boolean fijarLimiteNoticias(in long numero_maximo);
       oneway void shutdown();
    };
};
