spring:
  application:
    name: draftkingsManager
  config:
    import: "optional:configserver:http://localhost:8888"
server:
  port: 8081
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
  instance:
    hostname: localhost

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,refresh
info:
  application:
    name: ${spring.application.name}
    description: DraftKings manager microservice
    version: '@project.version@'

---
spring:
  config:
    activate:
      on-profile: dev
    import: "optional:configserver:https://dk-spring-config-dev.cnsa-2026-dsa069.tech/"
eureka:
  client:
    service-url:
      default-zone: https://dk-spring-eureka-dev.cnsa-2026-dsa069.tech/eureka/

server:
  port: ${PORT:8080}
info:
  application:
---
spring:
  config:
    activate:
      on-profile: prod
  import: "optional:configserver:http://dk-config-server:8080"
eureka:
  client:
    service-url:
      default-zone: http://dk-spring-eureka.cnsa-2026-dsa069.tech:8080
  instance:
    hostname: dk-spring-eureka.cnsa-2026-dsa069.tech
server:
  port: 8080