server:
  port: 8080

spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true                  

eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      default-zone: http://localhost:8761

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,refresh

info:
  application:
    name: ${spring.application.name}
    description: This is the API Gateway that centralizes access to all microservices
    version: '@project.version@'

---
spring:
  config:
    activate:
      on-profile: dev
    import: "optional:configserver:http://dk-config-server-dev:8080"
eureka:
  instance:
    hostname: dk-spring-eureka-dev.cnsa-2026-dsa069.tech
    client:
      service-url:
        default-zone: http://dk-spring-eureka-dev.cnsa-2026-dsa069.tech:8080
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: prod
  import: "optional:configserver:http://dk-config-server:8080"
eureka:
  instance:
    hostname: dk-spring-eureka.cnsa-2026-dsa069.tech
  client:
    service-url:
      default-zone: http://dk-spring-eureka.cnsa-2026-dsa069.tech:8080
server:
  port: 8080