spring:
 application:
  name: eurekaServer
 config:
  import: "optional:configserver:http://localhost:8888"
server:
 port: 8761
eureka:
 server:
  enable-self-preservation: false
 client:
  register-with-eureka: false
  fetch-registry: false

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,refresh
info:
  application:
    name: ${spring.application.name}
    description: Eureka server
    version: '@project.version@'

---
spring:
  config:
    activate:
      on-profile: dev
    import: "optional:configserver:https://dk-spring-config-dev.cnsa-2026-dsa069.tech/"
  cloud:
    config:
      fail-fast: false # No rompas el arranque si el config server falla
      request-connect-timeout: 2000 # 2 segundos para conectar
      request-read-timeout: 3000    # 3 segundos para leer datos

server:
  port: ${PORT:8080}

info:
  application:
    name: ${spring.application.name}
    description: Eureka server en dev profile
    version: '@project.version@'

---
spring:
  config:
    activate:
      on-profile: prod
    import: "optional:configserver:http://dk-config-server:8080"
server:
  port: ${PORT:8080}