package BufferApp;


/**
* BufferApp/BufferOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /workspaces/DraftKings/corba-services/DK_News_Manager/Buffer.idl
* Monday, May 4, 2026 8:29:44 PM UTC
*/

public interface BufferOperations 
{
  int num_elementos ();
  boolean put (String elemento);
  boolean get (org.omg.CORBA.StringHolder elemento);
  boolean read (org.omg.CORBA.StringHolder elemento);
  boolean fijarLimiteNoticias (int numero_maximo);
  void shutdown ();
} // interface BufferOperations
