package BufferApp;


/**
* BufferApp/Buffer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /workspaces/DraftKings/corba-services/DK_News_Manager/Buffer.idl
* Monday, May 4, 2026 8:29:44 PM UTC
*/

public interface Buffer extends BufferOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Buffer
