<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="gestorNoticias">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="noticia" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fecha">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[012])/\d{4}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                                <xs:element name="jugador">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:pattern value="(\s*\S\s*){2,50}"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:element>
                            <xs:element name="interes">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="alta"/>
                                        <xs:enumeration value="media"/>
                                        <xs:enumeration value="baja"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="titulo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="(\s*\S\s*){5,30}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="descripcion">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="(\s*\S\s*){20,250}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="etiquetas">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="etiqueta" minOccurs="1" maxOccurs="6">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="#\S+"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
