/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PlayerDashboard {
    }
    interface PlayerDetail {
        "player": any;
    }
    interface PlayerList {
    }
}
export interface PlayerDetailCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPlayerDetailElement;
}
export interface PlayerListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPlayerListElement;
}
declare global {
    interface HTMLPlayerDashboardElement extends Components.PlayerDashboard, HTMLStencilElement {
    }
    var HTMLPlayerDashboardElement: {
        prototype: HTMLPlayerDashboardElement;
        new (): HTMLPlayerDashboardElement;
    };
    interface HTMLPlayerDetailElementEventMap {
        "backToList": void;
    }
    interface HTMLPlayerDetailElement extends Components.PlayerDetail, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPlayerDetailElementEventMap>(type: K, listener: (this: HTMLPlayerDetailElement, ev: PlayerDetailCustomEvent<HTMLPlayerDetailElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPlayerDetailElementEventMap>(type: K, listener: (this: HTMLPlayerDetailElement, ev: PlayerDetailCustomEvent<HTMLPlayerDetailElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPlayerDetailElement: {
        prototype: HTMLPlayerDetailElement;
        new (): HTMLPlayerDetailElement;
    };
    interface HTMLPlayerListElementEventMap {
        "playerSelected": number;
    }
    interface HTMLPlayerListElement extends Components.PlayerList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPlayerListElementEventMap>(type: K, listener: (this: HTMLPlayerListElement, ev: PlayerListCustomEvent<HTMLPlayerListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPlayerListElementEventMap>(type: K, listener: (this: HTMLPlayerListElement, ev: PlayerListCustomEvent<HTMLPlayerListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPlayerListElement: {
        prototype: HTMLPlayerListElement;
        new (): HTMLPlayerListElement;
    };
    interface HTMLElementTagNameMap {
        "player-dashboard": HTMLPlayerDashboardElement;
        "player-detail": HTMLPlayerDetailElement;
        "player-list": HTMLPlayerListElement;
    }
}
declare namespace LocalJSX {
    interface PlayerDashboard {
    }
    interface PlayerDetail {
        "onBackToList"?: (event: PlayerDetailCustomEvent<void>) => void;
        "player"?: any;
    }
    interface PlayerList {
        "onPlayerSelected"?: (event: PlayerListCustomEvent<number>) => void;
    }

    interface PlayerDetailAttributes {
        "player": string;
    }

    interface IntrinsicElements {
        "player-dashboard": PlayerDashboard;
        "player-detail": Omit<PlayerDetail, keyof PlayerDetailAttributes> & { [K in keyof PlayerDetail & keyof PlayerDetailAttributes]?: PlayerDetail[K] } & { [K in keyof PlayerDetail & keyof PlayerDetailAttributes as `attr:${K}`]?: PlayerDetailAttributes[K] } & { [K in keyof PlayerDetail & keyof PlayerDetailAttributes as `prop:${K}`]?: PlayerDetail[K] };
        "player-list": PlayerList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "player-dashboard": LocalJSX.IntrinsicElements["player-dashboard"] & JSXBase.HTMLAttributes<HTMLPlayerDashboardElement>;
            "player-detail": LocalJSX.IntrinsicElements["player-detail"] & JSXBase.HTMLAttributes<HTMLPlayerDetailElement>;
            "player-list": LocalJSX.IntrinsicElements["player-list"] & JSXBase.HTMLAttributes<HTMLPlayerListElement>;
        }
    }
}
