server:
  port: ${PORT:8080}
eureka:
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      default-zone: https://dk-spring-eureka-dev.cnsa-2026-dsa069.tech/eureka/

spring:
  datasource:
    url: jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
    username: postgres.ixbdoxfxxlymwjuyfdiq
    password: ${DB_SQL_PASS_DEV}
    driver-class-name: org.postgresql.Driver

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
info:
  application:
    name: ${spring.application.name}
    description: Player microservice en desarrollo
    version: '@project.version@'
