server:
 port: ${PORT:8080}
eureka:
  instance:
    hostname: dk-spring-eureka.cnsa-2026-dsa069.tech
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      default-zone: http://dk-spring-eureka.cnsa-2026-dsa069.tech:8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:${DB_SQL_PASS_PROD}@db.vopcpjecorghtrqpvqtc.supabase.co:5432/postgres
    username: postgres
    password: ${DB_SQL_PASS_PROD}
    driver-class-name: org.postgresql.Driver

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
info:
  application:
    name: ${spring.application.name}
    description: Review microservice en produccion
    version: '@project.version@'
