server:
  port: ${PORT:8080}
eureka:
  instance:
    hostname: eureka-client-review-dev-223788394742.us-east1.run.app
    prefer-ip-address: false 
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443

    status-page-url: https://${eureka.instance.hostname}/actuator/info
    health-check-url: https://${eureka.instance.hostname}/actuator/health
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: https://dk-spring-eureka-dev.cnsa-2026-dsa069.tech/eureka/

spring:
  datasource:
    url: jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
    username: postgres.ixbdoxfxxlymwjuyfdiq
    password: ${DB_SQL_PASS_DEV}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # O 'none' si no quieres que toque las tablas
    show-sql: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
info:
  application:
    name: ${spring.application.name}
    description: Review microservice en desarrollo
    version: '@project.version@'
