server:
  port: ${PORT:8080}
eureka:
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: https://dk-spring-eureka-dev.cnsa-2026-dsa069.tech/eureka/

spring:
  datasource:
    url: jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
    username: postgres.ixbdoxfxxlymwjuyfdiq
    password: ${DB_SQL_PASS_DEV}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # O 'none' si no quieres que toque las tablas
    show-sql: true
  mvc:
    cors:
      configs:
        '[/**]':
          allowed-origins: "https://draftkings-dev.cnsa-2026-dsa069.tech"
          allowed-methods: "*"
          allowed-headers: "*"
          allow-credentials: true
  
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
info:
  application:
    name: ${spring.application.name}
    description: User microservice en desarrollo
    version: '@project.version@'
