FROM node:24-alpine

ENV NODE_ENV=production

# Crear directorio de la app
WORKDIR /app

# Copiar dependencias
COPY package*.json ./

# Instalar solo dependencias de producción
RUN npm ci --only=production

# Copiar código fuente
COPY dist/ ./dist/
COPY dashboard_server/views/ ./dist/dashboard_server/views/
COPY public/ ./public/

EXPOSE 8080

CMD [ "node", "dist/bin/www.js" ]