server:
  port: 8888
spring:
  application:
    name: configServer
  cloud:
    config:
      enabled: false
eureka:
  client:
    enabled: false

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
info:
  application:
    name: ${spring.application.name}
    description: Config Server for DraftKings microservices
    version: '@project.version@'
---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      server:
        git:
          default-label: main
