server:
  port: 8888
spring:
  application:
    name: configServer
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
eureka:
  client:
    enabled: false


management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
info:
  application:
    name: ${spring.application.name}
    description: Config Server for DraftKings microservices
    version: '@project.version@'
---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      server:
        git:
          default-label: main
