server:
  port: 8888
spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dsa069/DraftKings.git
          searchPaths: /api-spring/config-storage
          default-label: dev
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
  instance:
    hostname: localhost

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
info:
  application:
    name: ${spring.application.name}
    description: Config Server for DraftKings microservices
    version: '@project.version@'
---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      server:
        git:
          default-label: main
