server:
  port: 8091
spring:
  application:
    name: reviewMS
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:postgresql://postgresql/draftkings
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # O 'none' si no quieres que toque las tablas
    show-sql: true
    open-in-view: false
eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

openapi:
  title: DraftKings Review Microservice API
  description: API documentation for Review Microservice API that is part of the DraftKings application. This microservice manages review-related operations such as creating, retrieving, updating, and deleting reviews for players. It also provides endpoints to fetch reviews by user and player. The API is designed to be consumed by the frontend application and other microservices within the DraftKings ecosystem.
  version: '@project.version@'
  contact:
    name: Daniel Salas Alonso
    email: dsa069@inlumine.ual.es
    url: https://github.com/dsa069/DraftKings.git

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,refresh
info:
  application:
    name: ${spring.application.name}
    description: Review microservice
    version: '@project.version@'

---
spring:
  config:
    activate:
      on-profile: dev
    import: "optional:configserver:https://dk-spring-config-dev.cnsa-2026-dsa069.tech/"

server:
  port: ${PORT:8080}
info:
  application:
    description: DraftKings review microservice in dev profile
---
spring:
  config:
    activate:
      on-profile: prod
    import: "optional:configserver:https://dk-spring-config.cnsa-2026-dsa069.tech/"

server:
  port: ${PORT:8080}
info:
  application:
    description: DraftKings review microservice in prod profile

---
spring:
  config:
    activate:
      on-profile: test
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
server:
  port: ${PORT:8080}
info:
  application:
    description: DraftKings review microservice in test profile