server:
  port: 8091
spring:
  application:
    name: reviewMS
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:postgresql://postgresql/draftkings
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # O 'none' si no quieres que toque las tablas
    show-sql: true
eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,refresh
info:
  application:
    name: ${spring.application.name}
    description: Review microservice
    version: '@project.version@'

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
    username: postgres.ixbdoxfxxlymwjuyfdiq
    password: ${DB_SQL_PASS_DEV}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # O 'none' si no quieres que toque las tablas
    show-sql: true

eureka:
  instance:
    hostname: eureka-client-review-dev-223788394742.us-east1.run.app
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: https://dk-spring-eureka-dev.cnsa-2026-dsa069.tech/eureka/

server:
  port: ${PORT:8080}
info:
  application:
    description: DraftKings review microservice in dev profile
---
spring:
  config:
    activate:
      on-profile: prod
    import: "optional:configserver:https://dk-spring-config.cnsa-2026-dsa069.tech/"

server:
  port: ${PORT:8080}
info:
  application:
    description: DraftKings review microservice in prod profile