server:
  port: 8091
spring:
  application:
    name: reviewMS
  config:
    import: "optional:configserver:http://localhost:8888"

eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      default-zone: http://localhost:8761

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,refresh
info:
  application:
    name: ${spring.application.name}
    description: Review microservice
    version: '@project.version@'

---
spring:
  config:
    activate:
      on-profile: dev
    import: "optional:configserver:https://dk-spring-config-dev.cnsa-2026-dsa069.tech/"

server:
  port: ${PORT:8080}
info:
  application:
    description: DraftKings manager microservice in dev profile
---
spring:
  config:
    activate:
      on-profile: prod
    import: "optional:configserver:https://dk-spring-config.cnsa-2026-dsa069.tech/"
  datasource:
    url: jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
    username: postgres.vopcpjecorghtrqpvqtc
    password: ${DB_SQL_PASS_PROD}
    driver-class-name: org.postgresql.Driver

server:
  port: ${PORT:8080}
info:
  application:
    description: DraftKings manager microservice in prod profile