name: CI/CD Node

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write
    defaults:
      run:
        working-directory: ./api-node

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@v6.3.0
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: api-node/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload Artifacts (Build)
        uses: actions/upload-artifact@v7.0.1
        with:
          name: dist
          path: api-node/dist/

      - name: Save Code Linting Report JSON
        run: npm run lint:json
        continue-on-error: true

      - name: Test
        uses: mattallty/jest-github-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "npm run coverage"
          working-directory: "api-node"

      # --- ESTE ES EL PASO DE DEBUG ---
      - name: Debug - List Files (Ver dónde están los reportes)
        if: success() || failure()
        run: |
          echo "Contenido de la carpeta api-node:"
          ls -la
          echo "-----------------------------------"
          echo "Buscando archivos .xml en todo el proyecto:"
          find . -name "*.xml"
          echo "-----------------------------------"
          echo "Contenido de api-node/coverage (si existe):"
          ls -R coverage/ || echo "La carpeta coverage no existe en este nivel"

      - name: Upload Test Results and Coverage
        if: success() || failure()
        uses: actions/upload-artifact@v7.0.1
        with:
          name: test-results
          path: |
            ./api-node/coverage/test.results.xml
            ./api-node/coverage/

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v4
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "./api-node/coverage/eslint-result.json"

      - name: Test Report
        uses: dorny/test-reporter@v3.0.0
        with:
          artifact: test-results
          name: JEST Tests
          path: "test.results.xml"
          reporter: jest-junit
