name: CI/CD Node

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write
    defaults:
      run:
        working-directory: ./api-node

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@v6.3.0
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: api-node/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload Artifacts (Build)
        uses: actions/upload-artifact@v7.0.1
        with:
          name: dist
          path: api-node/dist/

      - name: Save Code Linting Report JSON
        run: npm run lint:json
        continue-on-error: true

      - name: Test
        uses: ArtiomTr/jest-coverage-report-action@v2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          output: report-markdown, comment
          working-directory: api-node
          skip-step: all
          coverage-file: report.json
          base-coverage-file: report.json

      - name: Post Summary
        if: always()
        run: |
          echo "## 📊 Reporte Completo de Cobertura" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.coverage_report.outputs.report }}" >> $GITHUB_STEP_SUMMARY

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v4
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "./api-node/coverage/eslint-result.json"
